### ISSUE TITLE
Question about formula （5） in 4.1 EquiConvs Details

### ISSUE THREAD

**Issue by FocusK** [cfernandezlab/CFL#10]
Thanks for your great work! 
      First, I meet some diffculty when I saw formula(5). I can't understand this formula, your aim is project each point in kernel into the sphere surface, but can you explain why your rotation matrix like this? And the code of rotation matrix is bot same with Rodrigues' Rotation Formula, I found when theta = pi/2, the result is different.
     Second, have you trid DCN-V1 or V2?

**Comment by cfernandezlab** [comment]
Hello! Thanks for writing!

For the rotation matrix we use Euler–Rodrigues formula associated with counterclockwise rotation, which is based on Rodrigues' rotation formula but uses a different parametrization. You can play with this notebook that I recently uploaded to visualize the deformed kernel on the equirectangular image at different positions: https://github.com/cfernandezlab/360-Scene-Understanding/tree/master/EquiConvs 

Regarding DCN, we used this implementation: https://github.com/Zardinality/TF_Deformable_Net, which was v1, but feel free to try v2 :)

**Comment by FocusK** [comment]
Thanks for your reply.  Best wishes for you!

**Comment by FocusK** [comment]
I am so sorry to trouble you again. I am not understand the code below. According to the paper,I know rays is pij = [i j d]，rays[0] is corresponding to i, rays[1] is corresponding to j, … but I can't know the role of K.  As you say in the paper, i and j are integer in the range [- (r-1)/2, (r-1)/2]. So why do you need to multiply inv_K and rays. 
    Another, the value of c_x and c_y is always 0? 

`
c_x = 0
c_y = 0
K = np.array([[d,0,c_x],[0,d,c_y],[0,0,1]])
inv_K = np.linalg.inv(K)
rays = np.matmul(inv_K, rays.reshape(3,r_h*r_w))
`
