### ISSUE TITLE
Error in deformable_im2col？

### ISSUE THREAD

**Issue by FocusK** [cfernandezlab/CFL#14]
Hi!
When I use EquiConv to train, an error occur: error in deformable_im2col: out of memory, and err = 2, cudaSuccess = 0, have you ever encountered this kind of error. Online solutions are ：change to a small model 、small dataset. If you are free
（1）Can you tell me the specific machine configuration during your training？ GPU……
（2） In your paper, the input of the network is image of 256128. So do you encountered similar errors when using larger images？If not, why image size is designed to be 256128?
（3）I know that  EquiConvs are built on top of deformable convolutions, the only difference is the way to get offset.  My question is whether we need to change the deformed convolution other than the way to find the offset？ I got the Deformablle_Convolution_pytorch from https://github.com/open-mmlab/mmdetection, then I only to change the way to find  offset in x.py?  And no need to change .cu and .cpp files that they define this op(DCN).
（4）Can you share train.py with me? I want to use your code to test whether equiconv can run on my computer. It ’s okay if it ’s inconvenient.
Thank you very much for your help during this time.

**Comment by cfernandezlab** [comment]
Hello!
I don't remember experiencing that error but you can try reducing the batch size.
1) GPU was NVIDIA Titan X
2) We didn't see any significant drop in performance and it's faster.
3) Exactly, you don't need to change anything in .cu and .cpp files
4) You can see if EquiConvs run on you computer with the test file already. As soon as I have time I will clean the training code and upload it.
Hope this helps.
