### ISSUE TITLE
A question about CE

### ISSUE THREAD

**Issue by FocusK** [cfernandezlab/CFL#15]
Hi！
Thanks for your great work! I have a question about CE, hoping to get your help.
In your code, I can't find how to calculate CE and PE. The output of network is an image, but I wonder how to get the corner id from Corner Map, especially for complete segmentation, can you spare your code or describe your method. Thank you!
Best wishes for you.

**Comment by cfernandezlab** [comment]
You can check [2Dto3D.ipynb](https://github.com/cfernandezlab/CFL/blob/master/2Dto3D.ipynb) to know how to obtain the 2D corners from the corner maps.

**Comment by FocusK** [comment]
Thanks for your reply,. When I open the link, the page has nothing
