### ISSUE TITLE
Hi. where can I get the model.ckpt ?

### ISSUE THREAD

**Issue by lixuran** [cfernandezlab/CFL#2]

**Comment by cfernandezlab** [comment]
Hi! To get the models please go to section 'Download Models' in the readme file. There you can find the links for both models, StdConvs and EquiConvs.

**Comment by lixuran** [comment]
Thank you, I can confirm that the shared models are accessible. 

By the way, if you don't mind, may I ask how did you acquire the original SUN360 dataset? I applied for the dataset but received no response from the author.

**Comment by cfernandezlab** [comment]
We prepared the dataset from the PanoContext data: http://panocontext.cs.princeton.edu/
The original link is: https://vision.princeton.edu/projects/2012/SUN360/data/

**Comment by ayj12345** [comment]
> Thank you, I can confirm that the shared models are accessible.
> 
> By the way, if you don't mind, may I ask how did you acquire the original SUN360 dataset? I applied for the dataset but received no response from the author.

I wonder if you could help me with this. Can you provide the link to download the models?  the link of the both models in the readme file are inaccessible in China.
