### ISSUE TITLE
How to recovery layout from the corner map and the edge map?

### ISSUE THREAD

**Issue by ayj12345** [cfernandezlab/CFL#3]

**Comment by ayj12345** [comment]
Answer my own question .
I think the most work  about  layout recover from panorama will reference this paper，“Y. Zhang, S. Song, P. Tan, and J. Xiao.PanoContext: A Whole-room 3D Context Model for Panoramic Scene Understanding.Proceedings of the 13th European Conference on Computer Vision [ECCV2014)”(http://panocontext.cs.princeton.edu/]
From 2D rectangle to 3D cuboid, [http://panocontext.cs.princeton.edu/supp.pdf].
Recovery Layout From the corner map, [http://panocontext.cs.princeton.edu/panorama.pdf].

**Comment by cfernandezlab** [comment]
Hi! Actually there is no single way to go from corner maps to 3D layouts, this is in fact one of the main challenges. You can check also LayoutNet, Layouts from Panoramic Images with Geometry and Deep Learning, ...
There is a direct relationship between spherical coordinates and pixel coordinates in equirectangular projection and this is one thing we all take into consideration. This give us the 3D ray that goes from the centre of the sphere to the position on the sphere surface we want. From this, several assumptions can be taken into account like the height of the camera, Manhattan World Assumption (3 main orthogonal directions) , horizontal  vanishing line known, 4-walls room setups...
In CFL for example we bet for not assuming 4-walls rooms anymore and for relaxing the Manhattan World assumption, usually referred as Soft/Weak Manhattan or Atlanta World. This means that the horizontal directions are not necessarily orthogonal to each other. 
In practice, floor and ceiling corners are projected to floor and ceiling planes respectively given a unitary camera height (trivial as results are up to scale) and assuming floor-ceiling parallelism.
By relaxing assumptions, we give greater credit to the corners directly predicted by the network without the need of generating layout hypotheses. This makes our model the fastest one by a large margin with respect to the SOTA.
I hope this clarifies your doubt.
